name: messcoin
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8

  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.1.2
  flutter_svg: ^2.1.0
  fl_chart: ^0.71.0
  open_file: ^3.5.10
  socket_io_client: ^3.1.2
  file_saver: ^0.2.14
  month_picker_dialog: ^6.4.1
  onesignal_flutter: ^5.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  
  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700